# Generated by Django 3.0.3 on 2020-07-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('Round 1', 'Round 1'), ('Round 2', 'Round 2'), ('Finale', 'Finale')], max_length=55, verbose_name='round')),
                ('group', models.CharField(choices=[('Group A', 'Group A'), ('Group B', 'Group B'), ('Group C', 'Group C'), ('Group D', 'Group D'), ('Group E', 'Group E'), ('Group F', 'Group F'), ('Group G', 'Group G'), ('Group H', 'Group H'), ('Group I', 'Group I'), ('Group J', 'Group J')], max_length=55, verbose_name='group')),
                ('category', models.CharField(choices=[('Recents', 'Recents'), ('Sports', 'Sports'), ('Tech', 'Tech'), ('Geography', 'Geography'), ('GK', 'GK')], max_length=55, verbose_name='category')),
                ('question', models.CharField(max_length=125, verbose_name='question')),
                ('answer', models.CharField(max_length=125, verbose_name='answer')),
            ],
        ),
    ]
