# Generated by Django 3.0.3 on 2020-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandFinale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('General Round', 'General ROund'), ('Buzzer Round', 'Buzzer Round'), ('Risk Round', 'Risk Round')], max_length=55, verbose_name='round')),
                ('category', models.CharField(choices=[('Recents', 'Recents'), ('Sports', 'Sports'), ('Tech', 'Tech'), ('Geography', 'Geography'), ('GK', 'GK'), ('Buzzer', 'Buzzer'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=55, verbose_name='category')),
                ('question', models.CharField(max_length=125, verbose_name='question')),
                ('image_question', models.ImageField(blank=True, null=True, upload_to='quiz_images')),
                ('answer', models.CharField(max_length=125, verbose_name='answer')),
            ],
        ),
    ]
