# Generated by Django 3.0.3 on 2020-09-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedin',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
    ]
